version: "3"

services:
  aud_manager:
    image: ghcr.io/sifis-home/aud_manager:latest
    network_mode: host
    ports:
      - 6060:6060/tcp

  watchtower:
    image: containrrr/watchtower
    command: --interval 30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
