FROM alpine:3.11

RUN apk --no-cache update   && \
    apk upgrade             && \
    apk add python3
RUN pip3 install flask ipwhois

COPY aud_sensor /home/aud_sensor
COPY modules /home/modules

VOLUME /tmp/aud
EXPOSE 5060/tcp

WORKDIR /home/aud_sensor
ENTRYPOINT ["/usr/bin/python3", "/home/aud_sensor/aud_sensor.py"]
